docker:
  cpu:
    image: ${ASKCOS_REGISTRY}/tree_search/expand_one:1.0-cpu
    build: docker build -f Dockerfile_cpu -t ${ASKCOS_REGISTRY}/tree_search/expand_one:1.0-cpu .
    start: sh scripts/serve_cpu_in_docker.sh

singularity:
  cpu:
    image: expand_one_cpu.sif
    build: singularity build -f expand_one_cpu.sif singularity_cpu.def
    start: sh scripts/serve_cpu_in_singularity.sh

commands:
  stop-docker: docker stop expand_one; docker rm expand_one
  stop-singularity: singularity instance stop expand_one
