docker:
  cpu:
    image: ${ASKCOS_REGISTRY}/tree_search/mcts:1.0-cpu
    build: docker build -f Dockerfile_cpu -t ${ASKCOS_REGISTRY}/tree_search/mcts:1.0-cpu .
    start: sh scripts/serve_cpu_in_docker.sh

singularity:
  cpu:
    image: mcts_cpu.sif
    build: singularity build -f mcts_cpu.sif singularity_cpu.def
    start: sh scripts/serve_cpu_in_singularity.sh

commands:
  stop-docker: docker stop mcts; docker rm mcts
  stop-singularity: singularity instance stop mcts
